// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AppsController from "./apps_controller"
application.register("apps", AppsController)

import CardsController from "./cards_controller"
application.register("cards", CardsController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FolderController from "./folder_controller"
application.register("folder", FolderController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PromptController from "./prompt_controller"
application.register("prompt", PromptController)
